---
title: "Homework Assignments"
output: 
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: cosmo
---

Homework assignments will appear here. You'll be able to access the assignment, as well as any data that may be used. Homework assignments will be posted **at least one week** before they are due. Submit homework assignments via Canvas by the due date and time.

## Homework 1
- [Homework 1 is here](homework/homework_1.html)
- Due on **9/14 by 9:30am**
- Peer Review of Homework 1 due *9/17 by 9:30am*

## Homework 2
- [Homework 2 is here](homework/homework_2.html)
- Due on **9/23 by 9:30am**
- Peer Review of Homework 2 due *9/26 by 9:30am*

## Homework 3
- [Homework 3 is here](homework/homework_3.html)
- Due on **10/21 by 9:30am**
- Peer Review of Homework 3 due *10/24 by 9:30am*

## Homework 4
- [Homework 4 is here](homework/homework_4.html)
- Due on **11/4 by 9:30am**
- Peer Review of Homework 4 due *11/7 by 9:30am*

## Homework 5
- [Homework 5 is here](homework/homework_5.html)
- Due on **12/7 by 9:30am**
- Peer Review of Homework 5 due *12/10 by 9:30am*

## Homework 6
- Not posted yet
- Due on **12/7 by 9:30am**
- Peer Review of Homework 6 due *12/10 by 9:30am*