---
title: "Lecture Videos"
output: 
  html_document:
    toc: TRUE
    toc_depth: 4
    toc_float: TRUE
    theme: cosmo
---

The following links should take you to the appropriate YouTube video.

## Week 1
#### 9/15

- [Introduction](https://youtu.be/0w6LF4Z0b60)
- [Zoom Link for Check-in 1 with Everyone](https://wustl.zoom.us/j/94508468165?pwd=ZlhqazhTTDliUWcrYUc0SHNVREc3dz09)

#### 9/17

- [Measurement Validity](https://youtu.be/ygvxDHE5In4)
- [Zoom Link for Check-in 1 with April](https://wustl.zoom.us/j/98006752991?pwd=ZHFFTmluUVJ3S3Z2R1lnaDVkODEvUT09)

## Week 2
#### 9/22

- [Describing Data Part 1](https://youtu.be/OeWELMpEbNQ)
- [Happiness Data](data/world_happiness_2015.csv) (used in the lecture)
- **Quiz 1 due by 9am**
- HW 1 posted

#### 9/24

- [Describing Data Part 2](https://youtu.be/bC3i5Zvkg8w)
- [Zoom Link for Check-in 3 with Shelly](https://wustl.zoom.us/j/94510139791?pwd=RDFnZjdiVW1QT1ZZR1h0OWpnUnQ1Zz09)

## Week 3
#### 9/29

- [Fisher Tradition & Probability](https://youtu.be/EvQ6nT5kP70)
- **HW 1 due by 9am**

#### 10/1

- [Binomial Distributions](https://youtu.be/nYWX4d3TDVo)
- [Normal Distributions](https://youtu.be/dTtfxVoB2XY)
- [Zoom Link for Check-in 4 with Jayde](https://wustl.zoom.us/j/95247533976?pwd=ZEZ3aTEzRzlEWURpaTJxYThqdktyUT09)

## Week 4
#### 10/6

- [Introduction to Bayesian Statistics](https://youtu.be/giLi4I9utZo)
- **Quiz 2 due by 9am**
- HW 2 posted

#### 10/8

- [Sampling distributions & $t$-distributions](https://youtu.be/H5hlZbuHuW4)
- [Zoom Link for Check-in 5 with Shelly](https://wustl.zoom.us/j/92791152076?pwd=Tmw3RFlpakVHemhoWVlyS1Y3WGpMQT09)
- [Recording of Zoom Check-in 5](https://youtu.be/a3RBql5_HpA)

## Week 5
#### 10/13

- **EXAM 1 OPENS**
  - Electronic copy will post to Canvas at 9:30am 
  - Hard copies available outside the Psychology Building (Somers Family Hall) from 8:30am-9:30am. I will be at the main entrance of the building (under the over-hang thing).
- **HW 2 due by 9am**

#### 10/15

- **EXAM 1 CLOSES**
  - Electronic versions must be submitted to Canvas by 9:30am
  - Hard copies must be returned to me between 8:30am-9:30am in the same location as the exam pick-up.
  
## Week 6
#### 10/20

- [Optional Video Re: Exam 1](https://youtu.be/JQldHHf9CHk)
- [Hypothesis Testing 1](https://youtu.be/2a4RHleMnh4)
- **Quiz 3 due by 9am**
- HW 3 posted

#### 10/22

- [Hypothesis Testing 2](https://youtu.be/uhCtguQF9aA)
- [Zoom Check-in 6 with April](https://wustl.zoom.us/j/94955983019?pwd=andNdmthbkZISGxDaFdwUGhNaFZEdz09)

## Week 7
#### 10/27

- [Critiques of NHST](https://youtu.be/rIJo_AjtzA0)
- **HW 3 due by 9am**

#### 10/29

- [Open Science Practices](https://youtu.be/vR59nHYKqoo)
- [Zoom Check-in 7 with Shelly](https://wustl.zoom.us/j/93074025592?pwd=bkFOS2FpaGFmcWxTQkNlNnRockdMZz09)

## Week 8
#### 11/3

- [Chi-Square Test](https://youtu.be/9oBpECAs4sc)
- **Quiz 4 due by 9am**
- HW 4 posted by noon

#### 11/5

- [One-sample tests](https://youtu.be/5Te2tZsqjD0)
- [Zoom Check-in 8 with Jayde](https://wustl.zoom.us/j/92763597580?pwd=UzJKSW0xemZBY3dIVTRob2s5T1dyUT09)

## Week 9
#### 11/10

- [Comparing Two Means -- Part A](https://youtu.be/P4_k1RtvmHo)
- [Comparing Two Means -- Part B](https://youtu.be/pX1X3eT8asA)

#### 11/12

- [Comparing Dependent Means](https://youtu.be/5Oj9RQnLWyM)
- [Zoom Check-in 9 with Shelly](https://wustl.zoom.us/j/92678939360?pwd=NHF4TCsxY1ppQWhIZGZtenMzRFpnUT09)

## Week 10
#### 11/17

- **Exam 2 Opens**

#### 11/19

- **Exam 2 Closes**

## Week 11
#### THANKSGIVING BREAK!

## Week 12
#### 12/1

- [Model Comparisons Approach](https://youtu.be/JIKigo20R3I)
  - *Note: There are slight errors on slides 18 & 36. The video recording added some corrections. Please pay attention to the video for those slides!*
- HW 5 posted

#### 12/3

- [Exam 2 Update/Thoughts](https://youtu.be/__YLhLlLqHU)
- [Oneway ANOVA](https://youtu.be/6qiWD8l34bg)
- [Zoom Check-in 10 with April](https://wustl.zoom.us/j/98200455792?pwd=WHlEYXB1WFZ0VUpaUTJ4Z1ZWMDNtUT09)

## Week 13
#### 12/8

- [Multiple Comparisons & Contrasts](https://youtu.be/0gCxl197Hmk)
- **HW 5 due by 9am**

#### 12/10

- Two between-subjects factors
  - Taught by our very own Jayde Homer!
- [Zoom Check-in 11 with Jayde](https://wustl.zoom.us/j/99714102106?pwd=aCtOMURzZkw3MFRhNXgvb2RIVFFtZz09)

## Week 14
#### 12/15

- Interactions & ANCOVA

#### 12/17

- Within-subjects designs
- **Quiz 6 due by 9am**
- [Zoom Check-in 12 with Shelly](https://wustl.zoom.us/j/91609788784?pwd=VktQSTE3RExscmF4Vk9ZYXFEdzR6QT09)