---
title: 'Psych 5066: Homework #3'
author: YOUR NAME HERE
output: 
  html_document
---

# Instructions

Please complete this assignment using the RMarkdown file provided (<a href="homework_3.Rmd" download="homework_3.Rmd">download here</a>). Be sure to include your name in the preamble. When you turn in the assignment, include **_both_** the .Rmd and knitted .html files. Please turn in both documents to the **ASSIGNMENTS** page *and* the **PEER REVIEW DISCUSSION** on Canvas.

There will be empty gray sections below each question. Please put all R `CODE` within these gray chunks. They will behave as normal R code. If you are asked to explain something or write a few sentences, please do that *outside* of the gray chunks. That way, when you knit, your sentences will show up as normal text, but all of your code will be in a designated code chunk.

You are allowed to Google things. *However*, if you use code from an outside source (meaning not the lecture slides or the R help documentation), then you must provide a **working link** to the website you used. You don't need to use APA formatting or anything. Just a working url. You may discuss homework assignments with your classmates; however, it is important that you complete each assignment on your own and **do not simply copy someone else’s code**. If we believe one student has copied another’s work, both students will receive a 0 on the homework assignment. Please also list at the top of the document who you worked with. 

In the instructions, when it says **_by hand_**, what we mean is that you should not use a function that is built into R to complete the task. For example, if I ask you to find the mean *by hand*, you should **not** use the `mean()` function. However, you can (and should!) use your variables. So for instance, if I ask you to find the `mean()` by hand, you may do something like `sum(variableX)/length(variableX)`. This would be an appropriate *by hand* calculation. (You don't need to type `(3 + 5 + 5 + 17) / 4`...you can still use your variables). 

You will be using the same census data that we used in class for our one-sample $t$-test. These data are specific to the state of Missouri [Here is the link for the census data](cenus_at_school_missouri.csv).

Good luck!

## Question 1

Students were asked how important access to the internet is to them, and to rate this importance on a scale of 0-1000 (see `Importance_Internet_access` variable) with 0 referring to not important and 1000 referring to very important. Do 9th graders (freshman) differ from 12th graders (seniors) in these ratings? Please do the following:

- Write a sentence or two stating the hypotheses
- Run the appropriate statistical test. Interpret the results in regards to your hypotheses.
- Calculate an appropriate effect size. Interpret results in terms of your hypotheses. 
- Make a figure showing this effect that includes all of the following:
  - The means
  - Variability around the means
  - Either the raw data or a distribution of data
  - Appropriate title, labeled axes etc.

## Question 2
High school students to rate the importance of reducing pollution on a scale of 0 (not important) to 1000 (very important). The nationwide average was 762. How well do students from Missouri align with the national average? Run and interpret your statistical test. Additionally, calculate confidence intervals "by hand" and interpret them.

## Question 3

You are interested in better understanding technology use and consumption among teenagers. However, you are concerned that in your sample of Missouri high school students that males might be more likely to prefer social media whereas females might be more likely to prefer text messaging. Run an appropriate statistical test and interpret the results. Calculate an appropriate measure of effect size (you may do this by hand or you may find a function...Google is your friend!)

## Question 4

Each student in the sample is a unique individual. However, let's assume that instead they collect census data of the same students over time (years 9, 10, 11, and 12 for the same students). Answer the following questions about this new setup:

- What is the name of this type of research design?
- If you are interested in the same question asked in Q1, how does your code need to change to reflect the changes in research design? 
- What are the pros and cons of this setup?
- Can you think of a time in your own research where you might use a similar setup? If so, describe it. If not, describe why this would not work for your research program.
- Ask us a question about how you might go about implementing or analyzing this type of design (for your own research or otherwise)! 

## Question 4

In your own words, describe this table. Do so in language that an average **freshman in high school** could understand (aka no jargon!)

|             |   Reject $H_0$   |   Do not reject  |
|------------:|:----------------:|:----------------:|
|  $H_0$ True |   $\alpha$   | $1-\alpha$ |
| $H_0$ False | $1-\beta$ |   $\beta$  |
