---
title: 'Psych 5066: Homework #4'
output: 
  html_document
---

# Instructions

- You will again make your own RMarkdown file. It must knit to a HTML file. And it must look pretty enough that Shelly, the AIs, and your peer review buddy can easily read your responses and your code.

- This HW assignment is about the use of Full/Restricted models. Please do your analyses using this frame work, "by hand" (aka as we have done in class several times). You may use an `R` function to double check your work if you wish (but not required).

- You must make use of formatted text and of code chunks. You need to show the appropriate output of your code so that we can evaluate it. For instance, if I ask for the mean of something, and you store it in an object *and do not print it out*, then we have no way of knowing if your mean value is correct. You must print it out. You do not need to print out an entire dataframe (although if you have the urge, you can use the `head()` function to show the first 6 rows).

- Please turn in both documents (the .Rmd and the .html) to the **ASSIGNMENTS** page *and* the **PEER REVIEW DISCUSSION** on Canvas.

# Data

The questions in this assignment use the dataset referred to as `homework-bdi`. [Link to data here.](homework-bdi.csv) For the problems below, we are interested in investigating the efficacy of an intervention to reduce depressive symptoms in a randomly sampled, community-based sample of adults. The participants completed the Beck Depression Inventory (BDI), and the data file includes the participants' scores on that dimension. Additionally, you will need [this dataset](homework-bdi-part2.csv) to complete question 3. 


Good luck!

## Question 1
For now, ignore the `condition` column of your data.frame and only pay attention to the scores. You recently read a literature review that suggested that your study population has an average BDI score of 14.

- Write out the restricted and full models for the analysis, in your own words (e.g., NOT equations)
- Conduct the appropriate analysis to compare these models. You must show all of your work! It's hard to see where you went wrong if we can't view what you calculated.
- Calculate an appropriate effect size for the analysis

## Question 2 

Participants were randomly assigned into either the intervention group or a waitlist control group,  scores reflect participants' BDI scores following the term of the intervention. In this dataset, 0 indicates participants in the control group, 1 indicates participants in the intervention group. 

- Write out the restricted and full models for the analysis, in your own words (e.g., NOT equations)
- Conduct the appropriate analysis to compare these models. You must show all of your work! It's hard to see where you went wrong if we can't view what you calculated.
- Calculate an appropriate effect size for the analysis

## Question 3

- Next, you need to combine the current dataset with the additional one. The new dataset includes new data with Condition 2. Merge the 2 datasets together to create a single data.frame
- Now assume that you have 3 groups (0 -- Control, 1 -- Intervention A, 2 -- Intervention B). Write out the restricted and full models for the oneway ANOVA of whether any group differences occur, in your own words (e.g., NOT equations)
- Conduct the appropriate analysis to compare these models
- Calculate an effect size measure for the overall ANOVA test of differences across groups

## Question 4

Provide an interpretation of each of the 3 analyses you just ran (3 total). Discuss how things changed when going from analysis 1 to analysis 2 (what happened to your $t$-statistic and effect size?).  
