---
title: 'Psych 5066: Homework #4'
output: 
  html_document
---

# Instructions

This assignment is going to be a little different than what we've done. Here's what's going to happen:

-   First, [watch this video on using RMarkdown](https://www.youtube.com/watch?v=z2a80FnLFfE) and customization. It is truly an EXCELLENT talk. Watching this is **required**.

-   You will create your own RMarkdown file, and you need to utilize at least 5 things from the video. It can range from themes, to inserting tables or equations, formatting the text to be bold/italics, bibliographies, formatting figures on the page etc. You can choose. But the resulting output document needs to look amazing.

-   In this gorgeous RMarkdown document that you create, you will answer the questions below. So the content will be the questions/answers, and the formatting better be 🔥

- Please turn in both documents to the **ASSIGNMENTS** page *and* the **PEER REVIEW DISCUSSION** on Canvas.

# Data

Please install the `palmerpenguins` package. This package contains 2 different datasets, one called `penguins` and the other called `penguins_raw`. Please use the `penguins` dataset for all of the questions below. I strongly suggest storing `penguins` as it's own object that you can work with in your environment.

Good luck!

## Question 1

Do certain islands produce more males or more females? State the null and alternative hypotheses, run the test, interpret the results.

## Question 2

Do certain islands produce more of one specie of penguin than other islands? State the null and alternative hypotheses, run the test, interpret the results.

## Question 3

In our hypothetical world, it is well-understood that the average body mass (in grams) of penguins worldwide is about 4200. Does your sample of Biscoe penguins differ from the average penguin? State the null and alternative hypotheses, run the test, interpret the results.

## Question 4

Do male and female penguins have similar bill lengths? State the null and alternative hypotheses, run the test, interpret the results.

