---
title: 'Models'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "my-theme.css"]
    incremental: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(base_color = "#17139C",link_color = "#DD3E3E")

```


## Kinds of research

- Experimental (we introduce an intervention and look at the effects; researcher introduced assignment)

- Observational (we measure/survey our participants without trying to affect them; no researcher-introduced assignment)



Typically we pair some kinds of statistical tests with experimental work and other kinds of tests with observational work.

---

## Kinds of research

In reality, most statistical tests can be used with most kinds of research. It's not so much the kind of research that matters, but __which statistic helps to answer your question__ and __what types of variables do you have?__

- We'll discuss the first point throughout the course
  
---

class: inverse, middle, center

# What is a model?

---

## What is a model?

- a representation of the world
- a **statistical** model uses math to make predictions about the world

--

**YOU DEFINE THE MODEL**

---
## Middle School Math

$$ y = mx + b $$
- what is $y$?
- what is $m$?
- what is $x$?
- what is $b$?

---

## Let's rewrite this

$$y = b_0 + b_{1}X$$ 
- what is $y$?
- what is $b_0$?
- what is $b_1$?
- what is $X$?

---
class: inverse, middle, center

# Are models always right?

---

# MODELS ARE FLAWED

- How? 

--

How do we compensate?

--

$y = b_0 + b_{1}X + e$


---

class: inverse, middle, center

# What are the goals of modeling?
# What do you need in order to develop a model?

---
class: inverse, middle, center

# How do we know if a model is good? What makes it good?
---

## How will we use models?

- This semester, we will mainly focus on classic statistical tests

- Every single one of these is a model

- We will also focus on developing your intuition 

- When you face new models, come back to these basics
