---
title: 'Within-Subjects Designs (and more)'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, rladies, rladies-fonts, "my-theme.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r packagesAndData, include=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(knitr)
library(kableExtra)
colors = RColorBrewer::brewer.pal(4, "Set2")
```

## Today

A series of shpiels 

- **Within-subjects designs**
- Non-parametric tests
- Exam 3 + semester wrap up

---

## Normality Assumption

---

## What happens when we don't meet assumptions?

---

## What's a "good" test?

---

## Which test to use

.small[
| Parametric Test | Situation | Non-Parametric Version|
|-----------------|-----------|-----------------------|
|Single sample *z* |Compare sample mean to population mean with known sigma | ¯\\_(ツ)_/¯  |
|Single sample *t* |Compare sample mean to population mean with unknown sigma |*Wilcoxon Signed-Rank Test*|
|Paired samples *t* |Compare 2 means with within-groups design|*Wilcoxon Signed-Rank Test*|
|Independent samples *t* |Compare 2 means with between-groups design|*Mann-Whitney U Test*|
|Oneway ANOVA (btwn groups)|Compare 3+ levels of IV|*Kruskal-Wallis H Test*|
|Oneway ANOVA (repeated measures)|Compare 3+ levels of IV|*Friedman Test* |
|Twoway ANOVA|2+ IVs (main effects/interactions)|*Kruskal-Wallis H Test* |
|Correlation| Relationship between 2 continuous vars| *Spearman Rank-Order Correlation*|
]